#!/bin/bash

set -e

usage() {
    echo "USAGE: git-practice-platform [-f | --folder <folder>] [-r | --repository <repository>] [-u | --usercount <count>]"
    exit 1
}

repo=
folder=
user_count=2
path=$(pwd)

realargs="$@"
while [ $# -gt 0 ]; do
    case "$1" in
        -r | --repository)
            repo=$2
            shift
        ;;
        -f | --folder)
            folder=$2
            shift
        ;;
        -u | --usercount)
            user_count=$2
            shift
        ;;
        *)
            usage
        ;;
    esac
    shift
done
set -- $realargs

if [ -z "$repo" ] || [ -z "$folder" ]; then
    usage
    return
fi

if [ -d "$path/$folder" ]; then
    echo "Folder already exists in $path/$folder"
    echo "Quited"
    exit 0
fi

root=${path}/${folder}
mkdir -p ${root}
echo "Root folder >>"
echo "    Created as ${root}"

mkdir -p ${root}/server/${repo}.git > /dev/null 2>&1
cd ${root}/server/${repo}.git
git init --bare > /dev/null 2>&1
echo "Bare repository >>"
echo "    Created under server/${repo}.git"

for (( i=1; i<=${user_count}; i++ ))
do
    echo "User${i} repository >>"

    mkdir -p ${root}/clients > /dev/null 2>&1
    mkdir -p ${root}/clients/user${i} > /dev/null 2>&1
    echo "    Created folder server/${repo}.git"

    cd ${root}/clients/user${i}
    git clone "file://${root}/server/${repo}.git" ${repo}.git > /dev/null 2>&1
    echo "    Cloned under clients/user${i}/${repo}.git"

    cd ${root}/clients/user${i}/${repo}.git
    git config user.name "User${i}"
    git config user.email "user${i}@gittraining.com"
    git config branch.autosetuprebase never
    git config branch.autosetupmerge true
    git config branch.master.rebase false
    git config alias.la "log --graph --all --pretty=format:'%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
    git config alias.lb "log --graph --pretty=format:'%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
    git config alias.lf "log --format=fuller"
    git config alias.l1 "log --stat --pretty=oneline"
    
    echo "    Applied initial git configurations"

done

echo "1 bare repository and ${user_count} clients are created. Ready for practicing."
