#!/bin/bash

set -e

fileNameNumberUpperLimit=100
commentNumberUpperLimit=1000

function getFileName() {
    randomNumber=$(( ( RANDOM % $fileNameNumberUpperLimit )  + 1 ))
    file="$1$randomNumber.$2"
    echo $file
}

function create() {
    if [ -f $1 ];
    then
        echo "Modified file $randomNumber" >> $1
        echo -n " ... modified"
    else
        echo "Created file $randomNumber" >> $1
        echo -n " ... created"
    fi
}

function isInGitRepo() {
    git rev-parse --is-inside-work-tree 2>/dev/null
    statusCode=$?
    if [ $statusCode -eq 0 ]; then
        echo 1
    else
        echo 0
    fi
}

function commitToGitRepo() {
    if [ -n "$1" ]; then
        git add -A
        randomNumber=$(( ( RANDOM % $commentNumberUpperLimit )  + 1 ))
        git commit -m "Random changes #${randomNumber}" >/dev/null 2>&1
        echo -n ", committed"
    fi
}

usage() { echo "USAGE: git-generate-changes -g -p <PREFIX> -c <NUMBER OF COMMITS> -e <EXTENSION>"; exit 1; }

prefix="temp"
count=1
extension="txt"
togit=

realargs="$@"
while [ $# -gt 0 ]; do
    case "$1" in
      -h | --help)
        usage
        ;;
      -p | --prefix)
        prefix=$2
        shift
        ;;
      -c | --count)
        count=$2
        shift
        ;;
      -e | --extension)
        extension=$2
        shift
        ;;
      -g | --commit)
        togit=1
        ;;
      *)
        usage
        break
        ;;
    esac
    shift
done
set -- $realargs

gitStatus=$(isInGitRepo)
if [ -n "$togit" ] && [ "$gitStatus" == true ]; then
    echo "FATAL: The current directory is not in a git repository"
    exit 0
fi

counter=1; 
while [[ $counter -le "$count" ]]; 
do
    file=$(getFileName $prefix $extension)
    echo -n "$file"
    create $file
    commitToGitRepo $togit
    echo ""
    let "counter += 1";
done


