#!/usr/bin/env zsh
source git-kata-functions

setup
create_upstream

#####################
switch_user tesla
#####################
initial_commit tesla

switch_branch feature
commit "settings.xml" "adds configuration of the project"
commit "procfile" "adds heroku settings to bootup with correct server configs"

switch_branch master
commit "readme" "creates an initial readme to add proper documentation"
commit ".gitignore" "adds initial gitignore file to ignore irrelevant files from git"

git push -u origin feature
git push -u origin master
display_log tesla

#####################
switch_user edison
#####################

switch_branch master

git pull origin master

commit "file1" "creates file1"
commit "file2" "creates file2"
git push origin master
display_log edison

#####################
switch_user tesla
#####################

switch_branch feature
git pull --rebase origin master
git push -f

# git fetch . origin/master:master
git fetch origin master:master
display_log tesla
