#!/bin/bash

set -e

usage() {
    echo "USAGE: live-git-reflog [-c | --count <max number of entries>]"
    exit 1
}

count=20

realargs="$@"
while [ $# -gt 0 ]; do
    case "$1" in
      -c | --count)
        count=$2
        break
        ;;
      *)
        usage
        ;;
    esac
    shift
done
set -- $realargs

while :
do
	clear
	git --no-pager reflog show -${count}
sleep 1
done
