#!/bin/bash

usage() {
    echo "USAGE: live-git-index [-a]"
    echo "   -a: [optional] show objects of all branches"
    exit 1
}

all=

while getopts ":a" option; do
    case "${option}" in
        a)
            all=1 ;;
        *)
            usage ;;
    esac
done
shift $((OPTIND-1))

while :
do
    clear
    echo "Current Branch with Staged Content:"
    echo "$( git ls-files -s )"
    echo ""

    if [ -n "$all" ]; then
        while read branch ; do
            echo "${branch}:"
            echo "$( git ls-tree -r $branch )"
            echo ""
        done < <( git for-each-ref --sort=-committerdate refs/heads/ --format='%(refname:short)' )
    fi
    sleep 1
done
